[project]
name = "krasnal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chess>=1.11.2",
    "datasets>=4.5.0",
    "matplotlib>=3.10.8",
    "notebook>=7.5.3",
    "nbqa>=1.9.1",
    "numpy>=2.4.2",
    "polars>=1.38.1",
    "pyarrow>=23.0.0",
    "pytest>=7.0.0",
    "ruff>=0.15.1",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
]

[tool.ruff]
line-length = 100
cache-dir = "~/.cache/ruff"
extend-include = ["*.ipynb"]


[tool.ruff.lint]
#syntax and runtime errors; logical errors; bug-risk; warnings; imports; pyupgrade; unused arguments
select = ["E", "F", "B", "W", "I", "UP", "ARG"]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["E402"]

[tool.pytest.ini_options]
pythonpath = "."

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
