learning_rate: 5e-4
min_lr: 5e-5
epochs: 1.0
warmup_iters: 100
batch_size: 32
num_workers: 4
pin_memory: true
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0
log_interval: 10
eval_interval: 5000
eval_num_games: 300
compile: true
compile_mode: default
compile_dynamic: false
compile_fullgraph: true
padding_bucket_sizes: [64, 128, 192, 256, 512]
