defaults:
  - _self_

seed: 42
side_prefixed_moves: true
piece_aware_moves: true
include_elo: true
time_control_token:
  enabled: true
opponent_material:
  enabled: true
outcome_conditioning:
  enabled: true
block_size: 512
wandb_project: krasnal

hydra:
  run:
    dir: .
