defaults:
  - _self_

seed: 42
side_prefixed_moves: true
piece_aware_moves: true
include_elo: true
block_size: 256
padding_bucket_sizes: [64, 128, 192, 256]  # make sure last bucket == block_size
wandb_project: krasnal

hydra:
  run:
    dir: .
