defaults:
  - pipeline
  - _self_

# Task-specific sampling probabilities
qa:
  check:
    enabled: true
    prob: 0.5
  piece_type_moved:
    enabled: true
    king_base_prob: 0.1
  what_is_on:
    enabled: true
    prob: 0.1

# Probability of hiding Elo information for one/both players
unknown_elo:
  normal_prob: 0.97
  white_unknown_prob: 0.01
  black_unknown_prob: 0.01
  both_unknown_prob: 0.01

preprocess_workers: 0
