defaults:
  - pipeline
  - model: small
  - train: cuda
  - eval: default
  - _self_

model_path: null
latest_pretrain: false
normal_dataset: data/2_tokenized/pretrain.parquet
cot_ratio: 0.5
cot_eval_shard_fraction: 0.1
max_iters: null
