name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  line-endings:
    name: Check Line Endings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for mixed line endings
        run: |
          found=$(git ls-files | xargs -I{} file "{}" | grep CRLF || true)
          if [ -n "$found" ]; then
            echo "ERROR: Files with CRLF line endings found:"
            echo "$found"
            exit 1
          fi

  python-lint:
    name: Python Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - run: pip install uv

      - name: Cache uv deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ hashFiles('uv.lock') }}

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff Check
        run: uv run ruff check .

      - name: Run Ruff Format Check
        run: uv run ruff format --check .

  python-test:
    name: Python Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - run: pip install uv

      - name: Cache uv deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ hashFiles('uv.lock') }}

      - name: Install dependencies
        run: uv sync

      - name: Run Pytest
        run: uv run pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
