name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rust-lint:
    name: Rust Clippy Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Apply autofix
        run: cargo clippy --fix --allow-dirty --all-targets --all-features

  python-lint:
    name: Python Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"
      - run: pip install uv

      - name: Cache uv deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ hashFiles('uv.lock') }}

      - name: Install dependencies
        run: uv sync

      - name: Cache Ruff
        uses: actions/cache@v4
        with:
          path: ~/.cache/ruff
          key: ruff-${{ hashFiles('pyproject.toml') }}

      - name: Run Ruff
        run: uv run ruff check . --fix

      - name: Run Ruff Format
        run: uv run ruff format .
